parameters:
#    ouss_blog.example.class: Ouss\BlogBundle\Example

services:
#    ouss_blog.example:
#        class: %ouss_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
